name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docker-build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - env: { COQ_VERSION: "master", DOCKER_COQ_VERSION: "dev" , DOCKER_MATHCOMP_VERSION: "1.17.0", DOCKER_OCAML_VERSION: "default", OPAM_DEPS: "coq-record-update coq-flocq", TGTS: "computed" }
        - env: { COQ_VERSION: "8.17"  , DOCKER_COQ_VERSION: "8.17", DOCKER_MATHCOMP_VERSION: "1.17.0", DOCKER_OCAML_VERSION: "default", OPAM_DEPS: "coq-record-update coq-flocq coq-interval coq-vcfloat coq-mathcomp-zify", TGTS: "" }

    runs-on: ubuntu-latest
    env: ${{ matrix.env }}
    name: ${{ matrix.env.COQ_VERSION }}

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.env.COQ_VERSION }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: coq-community/docker-coq-action@v1
      with:
        custom_image: mathcomp/mathcomp:${{ matrix.env.DOCKER_MATHCOMP_VERSION }}-coq-${{ matrix.env.DOCKER_COQ_VERSION }}
        #coq_version: ${{ matrix.env.DOCKER_COQ_VERSION }}
        #ocaml_version: ${{ matrix.env.DOCKER_OCAML_VERSION }}
        export: CI
        custom_script: |
          eval $(opam env)
          sudo chmod -R a=u .
          # Work around https://github.com/actions/checkout/issues/766
          git config --global --add safe.directory "*"
          echo '::group::install dependencies'
          opam install -y -v ${{ matrix.env.OPAM_DEPS }}
          echo '::endgroup::'
          make pretty-timed -j2
          make print-pretty-timed
