name: CI (Coq)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docker-build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - env: { COQ_VERSION: "master", DOCKER_COQ_VERSION: "dev" , DOCKER_MATHCOMP_VERSION: "1.17.0", DOCKER_OCAML_VERSION: "default", OPAM_DEPS: "coq-record-update coq-flocq", LAPROOF: "", TGTS: "computed", INSTALL_TGTS: "" }
        - env: { COQ_VERSION: "8.17"  , DOCKER_COQ_VERSION: "8.17", DOCKER_MATHCOMP_VERSION: "1.17.0", DOCKER_OCAML_VERSION: "default", OPAM_DEPS: "coq-record-update coq-flocq coq-interval coq-vcfloat coq-mathcomp-zify coq-mathcomp-analysis coq-mathcomp-algebra-tactics coq-mathcomp-finmap coq-vst coq-vst-lib", LAPROOF: "1", TGTS: "", INSTALL_TGTS: "install" }

    runs-on: ubuntu-latest
    env: ${{ matrix.env }}
    name: ${{ matrix.env.COQ_VERSION }}

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.env.COQ_VERSION }}-docker-build-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: coq-community/docker-coq-action@v1
      with:
        custom_image: mathcomp/mathcomp:${{ matrix.env.DOCKER_MATHCOMP_VERSION }}-coq-${{ matrix.env.DOCKER_COQ_VERSION }}
        #coq_version: ${{ matrix.env.DOCKER_COQ_VERSION }}
        #ocaml_version: ${{ matrix.env.DOCKER_OCAML_VERSION }}
        export: CI
        custom_script: |
          eval $(opam env)
          sudo chmod -R a=u .
          # Work around https://github.com/actions/checkout/issues/766
          git config --global --add safe.directory "*"
          echo '::group::install dependencies'
          opam install -y -v ${{ matrix.env.OPAM_DEPS }}
          echo '::endgroup::'
          echo '::group::install LAProof'
          if [ ! -z "${{ matrix.env.LAPROOF }}" ]; then
             git clone https://github.com/VeriNum/LAProof.git
             pushd LAProof
             git remote add JasonGross https://github.com/JasonGross/LAProof.git
             git remote update
             git checkout 7e5c81dcfafde501e87a2c2db4021f5190dff960 # waiting on https://github.com/VeriNum/LAProof/pull/10/
             make -j2 TIMED=1
             make install
             popd
          fi
          echo '::endgroup::'
          make pretty-timed -j2 TGTS="${{ matrix.env.TGTS }}"
          if [ ! -z "${{ matrix.env.INSTALL_TGTS }}" ]; then
             make ${{ matrix.env.INSTALL_TGTS }}
          fi
          make print-pretty-timed

  docker-build-native:
    strategy:
      fail-fast: false
      matrix:
        include:
        - env: { COQ_VERSION: "master", DOCKER_COQ_VERSION: "dev-native" , DOCKER_OCAML_VERSION: "default", OPAM_DEPS: "", LAPROOF: "", TGTS: "computed" }
        - env: { COQ_VERSION: "master (for Coq CI)", DOCKER_COQ_VERSION: "dev-native" , DOCKER_OCAML_VERSION: "default", OPAM_DEPS: "", LAPROOF: "", TGTS: "coq-ci-target" }

    runs-on: ubuntu-latest
    env: ${{ matrix.env }}
    name: ${{ matrix.env.COQ_VERSION }}

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.env.COQ_VERSION }}-docker-build-native-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: coq-community/docker-coq-action@v1
      with:
        coq_version: ${{ matrix.env.DOCKER_COQ_VERSION }}
        ocaml_version: ${{ matrix.env.DOCKER_OCAML_VERSION }}
        export: CI
        custom_script: |
          eval $(opam env)
          sudo chmod -R a=u .
          # Work around https://github.com/actions/checkout/issues/766
          git config --global --add safe.directory "*"
          echo '::group::install dependencies'
          if [ ! -z "${{ matrix.env.OPAM_DEPS }}" ]; then
             opam install -y -v ${{ matrix.env.OPAM_DEPS }}
          fi
          echo '::endgroup::'
          echo '::group::install LAProof'
          if [ ! -z "${{ matrix.env.LAPROOF }}" ]; then
             git clone https://github.com/VeriNum/LAProof.git
             pushd LAProof
             git remote add JasonGross https://github.com/JasonGross/LAProof.git
             git remote update
             git checkout 7e5c81dcfafde501e87a2c2db4021f5190dff960 # waiting on https://github.com/VeriNum/LAProof/pull/10/
             make -j2 TIMED=1
             make install
             popd
          fi
          echo '::endgroup::'
          make pretty-timed -j2 TGTS="${{ matrix.env.TGTS }}"
          make print-pretty-timed


  update-tested:
    name: Update tested
    needs: [docker-build, docker-build-native]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: 'tested'
        fetch-depth: 0
    - run: pwd
    - run: git fetch origin main
    - run: git log --oneline --max-count=10
    - run: git merge --ff-only remotes/origin/main
    - run: git log --oneline --max-count=10
    - run: git push
