name: CI (Python)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-python:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]

    runs-on: ubuntu-latest
    name: ${{ matrix.python-version }}

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.python-version }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        path: 'training'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        pwd
        python -m pip install --upgrade pip
        python -m pip install -r training/requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - run: make check
